name = "secure-messaging"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Enable observability for better debugging
[observability.logs]
enabled = true

[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionManager", script_name = "secure-messaging" },
  { name = "CONNECTIONS", class_name = "ConnectionManager", script_name = "secure-messaging" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionManager", "ConnectionManager"]

[vars]
ENVIRONMENT = "development"

# For production, set these via wrangler secret put
# TURNSTILE_SECRET_KEY = "your-secret-key"