name = "secure-messaging"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionManager" },
  { name = "CONNECTIONS", class_name = "ConnectionManager" }
]

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["SessionManager", "ConnectionManager"]

[vars]
ENVIRONMENT = "development"

# For production, set these via wrangler secret put
# TURNSTILE_SECRET_KEY = "your-secret-key"